# Generated by Django 5.2.8 on 2025-11-11 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100, verbose_name='目的地')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='预算')),
                ('participants', models.IntegerField(default=1, verbose_name='同行人数')),
                ('preferences', models.JSONField(default=list, verbose_name='旅行偏好')),
                ('special_requirements', models.TextField(blank=True, null=True, verbose_name='特殊需求')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=200, verbose_name='计划标题')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='计划摘要')),
                ('conversation_history', models.JSONField(default=list, help_text='\n        完整对话记录，格式:\n        [\n            {\n                "role": "user",\n                "content": "我想去日本",\n                "timestamp": "2025-11-11T10:00:00",\n                "turn": 1\n            },\n            {\n                "role": "assistant", \n                "content": {"summary": "日本5日游", "itinerary": {...}},\n                "timestamp": "2025-11-11T10:00:45",\n                "tokens_used": 1250,\n                "turn": 1\n            },\n            {\n                "role": "user",\n                "content": "预算增加到1.5万",\n                "timestamp": "2025-11-11T10:01:30", \n                "turn": 2\n            }\n        ]\n        ', verbose_name='对话历史')),
                ('itinerary', models.JSONField(default=list, verbose_name='行程安排')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '旅行计划',
                'verbose_name_plural': '旅行计划',
                'ordering': ['-created_at'],
            },
        ),
    ]
