# Generated by Django 5.2.8 on 2025-11-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelplan',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='预算'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='destination',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='目的地'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='preferences',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='旅行偏好'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
    ]
