# Generated by Django 5.2.8 on 2025-11-11 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_plans', '0002_alter_travelplan_budget_alter_travelplan_destination_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplan',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='conversation_history',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='special_requirements',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='travelplan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='travelplan',
            name='expenses',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='itinerary',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
