# Generated by Django 5.2.8 on 2025-11-12 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_plans', '0003_remove_travelplan_budget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='budget_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='currency',
            field=models.CharField(default='CNY', max_length=3),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='is_synced',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='sync_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='voice_notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='CNY', max_length=3)),
                ('category', models.CharField(choices=[('transportation', '交通'), ('accommodation', '住宿'), ('food', '餐饮'), ('entertainment', '娱乐'), ('shopping', '购物'), ('other', '其他')], default='other', max_length=50)),
                ('description', models.TextField()),
                ('location', models.JSONField(blank=True, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='expense_notes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_synced', models.BooleanField(default=True)),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_entries', to='travel_plans.travelplan')),
            ],
            options={
                'verbose_name': '费用条目',
                'verbose_name_plural': '费用条目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_preferences', models.JSONField(blank=True, default=dict)),
                ('voice_settings', models.JSONField(blank=True, default=dict)),
                ('sync_settings', models.JSONField(blank=True, default=dict)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('preferred_currency', models.CharField(default='CNY', max_length=3)),
                ('preferred_language', models.CharField(default='zh-CN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户配置',
                'verbose_name_plural': '用户配置',
            },
        ),
        migrations.CreateModel(
            name='VoiceInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='voice_recordings/')),
                ('transcription', models.TextField()),
                ('intent', models.CharField(choices=[('create_plan', '创建行程'), ('modify_plan', '修改行程'), ('add_expense', '添加费用'), ('query_plan', '查询行程'), ('general', '一般对话')], default='general', max_length=50)),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(default=0.0)),
                ('travel_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel_plans.travelplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '语音交互',
                'verbose_name_plural': '语音交互',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('llm', 'LLM服务'), ('voice', '语音识别'), ('tts', '语音合成'), ('maps', '地图服务')], max_length=20)),
                ('encrypted_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户API密钥',
                'verbose_name_plural': '用户API密钥',
                'unique_together': {('user', 'service')},
            },
        ),
    ]
