# Generated by Django 5.2.8 on 2025-11-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_plans', '0004_travelplan_budget_limit_travelplan_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapikey',
            name='service',
            field=models.CharField(choices=[('llm', 'LLM服务'), ('voice', '语音识别'), ('maps', '地图服务')], max_length=20),
        ),
    ]
