# Generated by Django 5.2.8 on 2025-11-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_plans', '0005_alter_userapikey_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='base_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userapikey',
            name='extra_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userapikey',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
