# Generated by Django 5.2.8 on 2025-11-12 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_plans', '0006_userapikey_base_url_userapikey_extra_config_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapikey',
            options={'verbose_name': '用户API密钥（已弃用）', 'verbose_name_plural': '用户API密钥（已弃用）'},
        ),
        migrations.CreateModel(
            name='LLMAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_url', models.URLField(help_text='API基础URL，如：https://api.openai.com/v1')),
                ('model_name', models.CharField(help_text='模型名称，如：gpt-3.5-turbo', max_length=100)),
                ('max_tokens', models.IntegerField(default=2048, help_text='最大token数')),
                ('temperature', models.FloatField(default=0.7, help_text='温度参数(0.0-2.0)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM API密钥',
                'verbose_name_plural': 'LLM API密钥',
                'unique_together': {('user',)},
            },
        ),
        migrations.CreateModel(
            name='MapAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('amap', '高德地图'), ('baidu', '百度地图'), ('google', 'Google Maps'), ('tencent', '腾讯地图')], default='amap', help_text='地图服务提供商', max_length=20)),
                ('base_url', models.URLField(blank=True, help_text='API基础URL（可选）', null=True)),
                ('daily_quota', models.IntegerField(default=10000, help_text='每日配额限制')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '地图服务 API密钥',
                'verbose_name_plural': '地图服务 API密钥',
                'unique_together': {('user',)},
            },
        ),
        migrations.CreateModel(
            name='VoiceAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('last_validated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_id', models.CharField(help_text='科大讯飞应用ID', max_length=50)),
                ('api_secret', models.TextField(help_text='科大讯飞API Secret（加密存储）')),
                ('language', models.CharField(choices=[('zh_cn', '中文普通话'), ('en_us', '英语'), ('zh_cantonese', '粤语')], default='zh_cn', help_text='识别语言', max_length=20)),
                ('accent', models.CharField(default='mandarin', help_text='口音设置', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '语音识别 API密钥',
                'verbose_name_plural': '语音识别 API密钥',
                'unique_together': {('user',)},
            },
        ),
    ]
