# Generated by Django 5.2.8 on 2025-11-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_plans', '0007_alter_userapikey_options_llmapikey_mapapikey_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='llmapikey',
            old_name='model_name',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='voiceapikey',
            name='api_secret',
        ),
        migrations.RemoveField(
            model_name='voiceapikey',
            name='app_id',
        ),
        migrations.AddField(
            model_name='voiceapikey',
            name='appid',
            field=models.CharField(default='', help_text='科大讯飞应用ID (APPID)', max_length=50),
        ),
        migrations.AddField(
            model_name='voiceapikey',
            name='encrypted_api_secret',
            field=models.TextField(default='', help_text='科大讯飞API Secret（加密存储）'),
        ),
    ]
