# Generated by Django 5.2.8 on 2025-11-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_plans', '0008_rename_model_name_llmapikey_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapapikey',
            options={'verbose_name': '高德地图 API密钥', 'verbose_name_plural': '高德地图 API密钥'},
        ),
        migrations.RemoveField(
            model_name='mapapikey',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='mapapikey',
            name='daily_quota',
        ),
        migrations.AlterField(
            model_name='mapapikey',
            name='provider',
            field=models.CharField(default='amap', editable=False, help_text='地图服务提供商（固定为高德地图）', max_length=20),
        ),
    ]
